/*
 *    Copyright 2020 Mateusz Armatys
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.nofrills.multimodule

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertNull

class MultimodulePluginTest {
    @Test
    fun `aar extensions`() {
        val (root, p) = testProjects("aar")
        assertNotNull(root.extensions.findByName("multimodule"))
        assertNotNull(p.extensions.findByName("submodule"))
    }

    @Test
    fun `apk extensions`() {
        val (root, p) = testProjects("apk")
        assertNotNull(root.extensions.findByName("multimodule"))
        assertNotNull(p.extensions.findByName("submodule"))
    }

    @Test
    fun `jar extensions`() {
        val (root, p) = testProjects("jar")
        assertNotNull(root.extensions.findByName("multimodule"))
        assertNotNull(p.extensions.findByName("submodule"))
    }

    @Test
    fun `applies android library plugin`() {
        val (_, p) = testProjects("aar")
        assertNotNull(p.plugins.findPlugin("com.android.library"))
    }

    @Test
    fun `applies android app plugin`() {
        val (_, p) = testProjects("apk")
        assertNotNull(p.plugins.findPlugin("com.android.application"))
    }

    @Test
    fun `applies java library plugin`() {
        val (_, p) = testProjects("jar")
        assertNotNull(p.plugins.findPlugin("java-library"))
        assertNull(p.plugins.findPlugin("com.android.application"))
        assertNull(p.plugins.findPlugin("com.android.library"))
    }
}
